#!/bin/bash

echo "=== MMRY Scrolling Functionality Test ==="
echo ""

# Start MMRY in background
echo "Starting MMRY..."
./cpp/build/bin/mmry_cpp &
MMRY_PID=$!

sleep 2

echo "Application started with PID: $MMRY_PID"
echo ""

echo "Manual test instructions for scrolling:"
echo ""
echo "1. MAIN CLIPS LIST SCROLLING:"
echo "   - Add many clipboard items (more than can fit on screen)"
echo "   - Use j/k to navigate - should scroll when reaching edges"
echo "   - Use 'gg' to go to top - should scroll to top"
echo "   - Use 'Shift+G' to go to bottom - should scroll to bottom"
echo "   - Check for scroll indicator [current/total] in top-right"
echo "   - Selected item should always remain visible"
echo ""
echo "2. BOOKMARK MANAGEMENT DIALOG (Shift+M):"
echo "   - Create many bookmark groups (more than 8)"
echo "   - Use j/k or arrow keys to navigate - should scroll"
echo "   - Use 'gg' to go to top, 'Shift+G' to go to bottom"
echo "   - Check for scroll indicator [current/total]"
echo "   - Selected group should always remain visible"
echo ""
echo "3. ADD BOOKMARK DIALOG (m):"
echo "   - With many bookmark groups, press 'm'"
echo "   - Use j/k to navigate - should scroll"
echo "   - Use 'gg' to go to top, 'Shift+G' to go to bottom"
echo "   - Check for scroll indicator [current/total]"
echo "   - Selected group should always remain visible"
echo ""
echo "4. VIEW BOOKMARKS DIALOG (backtick key):"
echo "   - Create a bookmark group with many clips"
echo "   - Press \` to view bookmarks, select the group"
echo "   - Use j/k to navigate clips - should scroll"
echo "   - Use 'gg' to go to top, 'Shift+G' to go to bottom"
echo "   - Check for scroll indicator [current/total]"
echo "   - Selected clip should always remain visible"
echo ""
echo "5. HELP DIALOG (?):"
echo "   - Press '?' to verify text fits within dialog boundaries"
echo "   - No overflow should be visible"
echo ""
echo "Expected behavior:"
echo "- All dialogs support j/k/gg/Shift+G navigation"
echo "- All dialogs show scroll indicators when content overflows"
echo "- Selected items always stay visible during scrolling"
echo "- Help dialog text fits within 500px dialog boundaries"
echo ""
echo "To stop test: kill $MMRY_PID"
echo ""
echo "Press Ctrl+Alt+C to show window and test scrolling features"